-- Brand / franchise ownership, deliberately separate from individual shop ownership.
alter type public.app_role add value if not exists 'brand_head';
create table public.brands (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.brand_members (brand_id uuid not null references public.brands(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in ('head','manager')), created_at timestamptz not null default now(), primary key(brand_id,user_id));
create table public.brand_handoffs (id uuid primary key default gen_random_uuid(), brand_id uuid not null references public.brands(id) on delete cascade, business_id uuid not null references public.businesses(id) on delete cascade, from_owner_id uuid not null references auth.users(id), to_owner_email text not null, to_owner_id uuid references auth.users(id), status text not null default 'pending' check(status in('pending','accepted','cancelled')), created_at timestamptz not null default now(), accepted_at timestamptz);
alter table public.brands enable row level security; alter table public.brand_members enable row level security; alter table public.brand_handoffs enable row level security;
create or replace function public.is_brand_member(_brand uuid,_user uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.brand_members where brand_id=_brand and user_id=_user)$$;
create policy "brands_member_read" on public.brands for select to authenticated using(public.is_brand_member(id,auth.uid()) or public.has_role(auth.uid(),'admin'));
create policy "brand_members_member_read" on public.brand_members for select to authenticated using(public.is_brand_member(brand_id,auth.uid()) or public.has_role(auth.uid(),'admin'));
create policy "brand_handoffs_participant_read" on public.brand_handoffs for select to authenticated using(public.is_brand_member(brand_id,auth.uid()) or to_owner_id=auth.uid() or public.has_role(auth.uid(),'admin'));
grant select on public.brands,public.brand_members,public.brand_handoffs to authenticated;

create or replace function public.create_brand(_name text,_slug text) returns uuid language plpgsql security definer set search_path=public as $$declare _id uuid;begin if auth.uid() is null then raise exception 'not authenticated';end if;insert into public.brands(name,slug,created_by) values(trim(_name),lower(trim(_slug)),auth.uid()) returning id into _id;insert into public.brand_members values(_id,auth.uid(),'head');insert into public.user_roles(user_id,role) values(auth.uid(),'brand_head') on conflict do nothing;return _id;end;$$;
create or replace function public.brand_create_shop(_brand uuid,_owner_email text,_name text,_slug text) returns uuid language plpgsql security definer set search_path=public as $$declare _owner uuid;_id uuid;begin if not public.is_brand_member(_brand,auth.uid()) then raise exception 'brand access required';end if;select id into _owner from auth.users where lower(email)=lower(trim(_owner_email));if _owner is null then raise exception 'the new shop owner must create an account first';end if;insert into public.businesses(owner_id,brand_id,name,slug) values(_owner,_brand,trim(_name),lower(trim(_slug))) returning id into _id;insert into public.user_roles(user_id,role) values(_owner,'business_owner') on conflict do nothing;return _id;end;$$;
create or replace function public.brand_rollup(_brand uuid) returns table(shop_count bigint,member_count bigint,stamps_30d bigint,rewards_redeemed_30d bigint) language sql stable security definer set search_path=public as $$select count(distinct b.id),count(distinct m.id),count(distinct t.id) filter(where t.type='stamp' and t.created_at>=now()-interval '30 days'),count(distinct r.id) filter(where r.redeemed_at>=now()-interval '30 days') from public.businesses b left join public.memberships m on m.business_id=b.id left join public.transactions t on t.business_id=b.id left join public.rewards r on r.business_id=b.id where b.brand_id=_brand and public.is_brand_member(_brand,auth.uid())$$;
create or replace function public.start_brand_handoff(_business uuid,_new_owner_email text) returns uuid language plpgsql security definer set search_path=public as $$declare _brand uuid;_id uuid;begin select brand_id into _brand from public.businesses where id=_business; if _brand is null or not public.is_brand_member(_brand,auth.uid()) then raise exception 'brand access required';end if;insert into public.brand_handoffs(brand_id,business_id,from_owner_id,to_owner_email) values(_brand,_business,auth.uid(),lower(trim(_new_owner_email))) returning id into _id;return _id;end;$$;
create or replace function public.accept_brand_handoff(_handoff uuid) returns void language plpgsql security definer set search_path=public as $$declare h public.brand_handoffs;begin select * into h from public.brand_handoffs where id=_handoff for update;if not found or h.status<>'pending' then raise exception 'handoff unavailable';end if;if lower((select email from auth.users where id=auth.uid()))<>h.to_owner_email then raise exception 'this handoff is for another account';end if;update public.businesses set owner_id=auth.uid() where id=h.business_id;insert into public.user_roles(user_id,role) values(auth.uid(),'business_owner') on conflict do nothing;update public.brand_handoffs set to_owner_id=auth.uid(),status='accepted',accepted_at=now() where id=h.id;end;$$;
revoke all on function public.create_brand(text,text),public.brand_create_shop(uuid,text,text,text),public.brand_rollup(uuid),public.start_brand_handoff(uuid,text),public.accept_brand_handoff(uuid) from public;
grant execute on function public.create_brand(text,text),public.brand_create_shop(uuid,text,text,text),public.brand_rollup(uuid),public.start_brand_handoff(uuid,text),public.accept_brand_handoff(uuid) to authenticated;
