import React from 'react'
import { FlexWidget, ImageWidget, TextWidget } from 'react-native-android-widget'
import type { RetailerWidgetState } from './state'

type Hex = `#${string}`
const DEFAULT_BRAND: Hex = '#EF7136'
// 96x96 scan-frame glyph (ink on transparent), generated by scratch script; embedded so
// the widget never depends on asset resolution inside the background task.
const SCAN_ICON = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAAs0lEQVR42u3csQ0AIAgAQQbRwv2H1N7EFjHeJwwgV9EYIUmSJElbfbSZOd4DAAAAAAAAAAAAAAAAAAWW9vKRCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEmSJElKP1YqDwAAAAAAAAAAAAAAACRJkiT9kGPl8m4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg+3oAAAAAAAAAAAAAAAAAcKRKkiRJOrcAlpXuU9U1Q6EAAAAASUVORK5CYII=' as `data:image${string}`

function asHex(value?: string | null): Hex {
  return value && /^#[0-9a-fA-F]{6}$/.test(value) ? (value as Hex) : DEFAULT_BRAND
}

/** Multiply each RGB channel by `factor` (0-1 darkens). */
function shade(color: Hex, factor: number): Hex {
  const n = parseInt(color.slice(1), 16)
  const channel = (shift: number) => Math.max(0, Math.min(255, Math.round(((n >> shift) & 255) * factor)))
  return `#${[channel(16), channel(8), channel(0)].map((v) => v.toString(16).padStart(2, '0')).join('')}`
}

const initialOf = (name: string) => (name.trim()[0] || 'L').toUpperCase()

/** Home-screen widget: brand gradient card with the shop badge, today's visit
 * count, member count and a big white "scan" button. Tapping anywhere opens the
 * scanner via the loyaltyloop-business://widget/scan deep link. */
export function renderRetailerWidget(state: RetailerWidgetState) {
  const brand = asHex(state.brandColor)
  const logo = state.logoUrl && /^https:\/\//.test(state.logoUrl) ? (state.logoUrl as `https:${string}`) : null
  const visits = state.todayActions
  const members = `${state.members} ${state.members === 1 ? 'member' : 'members'} on your card`
  return (
    <FlexWidget
      clickAction="OPEN_URI"
      clickActionData={{ uri: 'loyaltyloop-business://widget/scan' }}
      accessibilityLabel={`Open the scanner for ${state.businessName}. ${visits} visits today. ${members}.`}
      style={{
        width: 'match_parent',
        height: 'match_parent',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundGradient: { from: brand, to: shade(brand, 0.66), orientation: 'TL_BR' },
        borderRadius: 26,
        padding: 16,
      }}
    >
      <FlexWidget style={{ flex: 1, height: 'match_parent', flexDirection: 'column', justifyContent: 'space-between' }}>
        <FlexWidget style={{ flexDirection: 'row', alignItems: 'center' }}>
          {logo ? (
            <ImageWidget image={logo} imageWidth={34} imageHeight={34} radius={17} />
          ) : (
            <FlexWidget style={{ width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(255, 255, 255, 0.28)', alignItems: 'center', justifyContent: 'center' }}>
              <TextWidget text={initialOf(state.businessName)} style={{ color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' }} />
            </FlexWidget>
          )}
          <TextWidget text={state.businessName} maxLines={1} truncate="END" style={{ color: '#FFFFFF', fontSize: 15, fontWeight: 'bold', marginLeft: 10 }} />
        </FlexWidget>
        <FlexWidget style={{ flexDirection: 'column' }}>
          <TextWidget text={String(visits)} style={{ color: '#FFFFFF', fontSize: 38, fontWeight: 'bold' }} />
          <TextWidget text={visits === 1 ? 'visit today' : 'visits today'} style={{ color: 'rgba(255, 255, 255, 0.88)', fontSize: 13, marginTop: -2 }} />
        </FlexWidget>
        <TextWidget text={members} maxLines={1} truncate="END" style={{ color: 'rgba(255, 255, 255, 0.8)', fontSize: 12 }} />
      </FlexWidget>
      <FlexWidget style={{ flexDirection: 'column', alignItems: 'center', justifyContent: 'center', marginLeft: 12 }}>
        <FlexWidget style={{ width: 84, height: 84, borderRadius: 42, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' }}>
          <ImageWidget image={SCAN_ICON} imageWidth={40} imageHeight={40} />
        </FlexWidget>
        <TextWidget text="SCAN" style={{ color: '#FFFFFF', fontSize: 12, fontWeight: 'bold', letterSpacing: 0.12, marginTop: 8 }} />
      </FlexWidget>
    </FlexWidget>
  )
}
