import * as React from 'react'
import { supabase } from '@/lib/supabase'
const input = 'mt-2 w-full rounded-xl border border-white/15 bg-black/20 px-3 h-10 text-sm text-white'
export function AccessTools() {
  const [email, setEmail] = React.useState(''); const [role, setRole] = React.useState('consumer'); const [message, setMessage] = React.useState(''); const [ann, setAnn] = React.useState({ title: '', body: '' }); const [businessId, setBusinessId] = React.useState(''); const [threshold, setThreshold] = React.useState(10)
  const act = async (work: () => PromiseLike<unknown>, success: string) => { try { await work(); setMessage(success) } catch (error) { setMessage(error instanceof Error ? error.message : 'Action failed') } }
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl bg-white/6 p-6"><h2 className="font-display text-xl font-bold">Roles</h2><input className={input} value={email} onChange={e => setEmail(e.target.value)} placeholder="Account email"/><select className={input} value={role} onChange={e => setRole(e.target.value)}><option value="consumer">Consumer</option><option value="business_owner">Business owner</option><option value="staff">Staff</option><option value="admin">Admin</option></select><div className="mt-3 flex gap-2"><button onClick={() => act(() => supabase.rpc('admin_set_role', { _email: email, _role: role, _grant: true }), 'Role granted.')} className="rounded-xl bg-fun-green px-4 py-2 text-sm font-bold">Grant</button><button onClick={() => act(() => supabase.rpc('admin_set_role', { _email: email, _role: role, _grant: false }), 'Role revoked.')} className="rounded-xl border border-red-400/50 px-4 py-2 text-sm font-bold text-red-300">Revoke</button></div></section>
    <section className="rounded-2xl bg-white/6 p-6"><h2 className="font-display text-xl font-bold">Loyalty override</h2><input className={input} value={businessId} onChange={e => setBusinessId(e.target.value)} placeholder="Business UUID"/><input className={input} type="number" min="1" value={threshold} onChange={e => setThreshold(Number(e.target.value))}/><button onClick={() => act(() => supabase.rpc('admin_override_loyalty_threshold', { _business_id: businessId, _threshold: threshold }), 'Threshold updated and audited.')} className="mt-3 rounded-xl bg-primary px-4 py-2 text-sm font-bold">Override threshold</button></section>
    <section className="rounded-2xl bg-white/6 p-6"><h2 className="font-display text-xl font-bold">Platform announcement</h2><input className={input} value={ann.title} onChange={e => setAnn({ ...ann, title: e.target.value })} placeholder="Title"/><textarea className="mt-2 w-full rounded-xl border border-white/15 bg-black/20 p-3 text-sm text-white" value={ann.body} onChange={e => setAnn({ ...ann, body: e.target.value })} placeholder="Message"/><button onClick={() => act(() => supabase.from('platform_announcements').insert(ann), 'Announcement published to customer inboxes.')} className="mt-3 rounded-xl bg-primary px-4 py-2 text-sm font-bold">Publish</button></section>
    {message && <p className="text-sm text-[#5ACA64] lg:col-span-2">{message}</p>}
  </div>
}
