import * as React from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { Bell, CheckCheck } from 'lucide-react'
import { useAuth } from '@/lib/auth-context'
import { DashboardLayout } from '@/components/dashboard-layout'
import { PageSkeleton } from '@/components/page-skeleton'
import { fetchInbox, markAllInboxRead, markInboxRead, type InboxItem } from '@/lib/engagement'
export function InboxPage() { const {session,loading}=useAuth(); const nav=useNavigate(); const [items,setItems]=React.useState<InboxItem[]>([]); const [ready,setReady]=React.useState(false)
 React.useEffect(()=>{if(session?.user) fetchInbox(session.user.id).then(setItems).finally(()=>setReady(true))},[session?.user]); if(loading||!ready)return <PageSkeleton variant="feed" />;if(!session)return <Navigate to="/login" replace/>;
 const read=(id:string)=>{markInboxRead(id);setItems(a=>a.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x))}; const all=()=>{markAllInboxRead(session.user.id);setItems(a=>a.map(x=>({...x,read_at:x.read_at??new Date().toISOString()})))};
 return <DashboardLayout><div className="flex flex-wrap items-end justify-between gap-3"><h1 className="text-3xl font-display font-bold tracking-tight sm:text-4xl">Notification inbox</h1><button data-press-feedback onClick={all} className="flex items-center gap-2 rounded-full px-3.5 py-2 text-sm font-semibold text-foreground ring-1 ring-foreground/10 transition-colors hover:bg-secondary"><CheckCheck className="h-4 w-4"/>Mark all read</button></div><div className="mt-8 rounded-2xl bg-card ring-1 ring-foreground/8 divide-y divide-border overflow-hidden">{items.length?items.map(x=><button data-press-feedback key={x.id} onClick={()=>{read(x.id);if(x.link)nav(x.link)}} className={'w-full text-left p-5 flex gap-4 transition-colors hover:bg-secondary/60 '+(!x.read_at?'bg-peach/45':'')}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-peach text-peach-ink"><Bell className="h-5 w-5"/></span><div className="flex-1"><p className="font-semibold">{x.title}</p><p className="text-sm text-muted-foreground">{x.body}</p><p className="text-xs text-muted-foreground mt-2">{x.business?.name ? `${x.business.name} · `:''}{new Date(x.created_at).toLocaleString()}</p></div>{!x.read_at&&<span className="h-2.5 w-2.5 rounded-full bg-primary shrink-0 mt-2"/>}</button>):<div className="bg-sage p-10 text-center text-sage-ink">You’re all caught up.</div>}</div></DashboardLayout> }
